In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
data = pd.read_csv('data.csv')

In [3]:
data.head()

article_no                discipline            subdiscipline  \
0        1892               Biomedicine                Neurology   
1         586  Medicine & Public Health               Cardiology   
2        1603               Biomedicine               Immunology   
3        3341               Biomedicine  Pharmacology-Toxicology   
4        2561               Biomedicine                Neurology   

                   journal_title                             journal_url  \
0              Neurotherapeutics  http://link.springer.com/journal/13311   
1    Clinical Autonomic Research  http://link.springer.com/journal/10286   
2  Inflammation and Regeneration  http://link.springer.com/journal/41232   
3      Cardiovascular Toxicology  http://link.springer.com/journal/12012   
4        Metabolic Brain Disease  http://link.springer.com/journal/11011   

   volume issue     month  year                                     issue_url  \
0      16     2     April  2019  https://link.springer.com/journal/13311/16/2   
1      29     2     April  2019  https://link.springer.com/journal/10286/29/2   
2      38     1  December  2018  https://link.springer.com/journal/41232/38/1   
3      18     3      June  2018  https://link.springer.com/journal/12012/18/3   
4      31     6  December  2016  https://link.springer.com/journal/11011/31/6   

               type                                              title  \
0  Original Article  TET1 Overexpression Mitigates Neuropathic Pain...   
1    Review Article  The renin–angiotensin system in cardiovascular...   
2            Review  New application of anti-TLR monoclonal antibod...   
3    Original Paper  Alleviation of Cardiac Damage by Dietary Fenug...   
4  Original Article  Agomelatine reduces brain, kidney and liver ox...   

                                         article_url  \
0  https://link.springer.com/article/10.1007/s133...   
1  https://link.springer.com/article/10.1007/s102...   
2  https://link.springer.com/article/10.1186/s412...   
3  https://link.springer.com/article/10.1007/s120...   
4  https://link.springer.com/article/10.1007/s110...   

                                                text  
0  Introduction\nApproximately 7% of the world’s ...  
1  Introduction\nCardiovascular disease remains t...  
2  Background\nToll-like receptors (TLRs) recogni...  
3  Introduction\nDiabetes mellitus (DM) is the mo...  
4  Introduction\nOxidative stress occurs in the b...

In [ ]:
from transformers import pipeline, AutoModelForTokenClassification, AutoTokenizer


pipeline('sentiment-analysis')


pipeline('question-answering', model='distilbert-base-cased-distilled-squad', tokenizer='bert-base-cased')

model = AutoModelForTokenClassification.from_pretrained("dbmdz/bert-large-cased-finetuned-conll03-english")
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
pipeline('ner', model=model, tokenizer=tokenizer)

In [6]:
from transformers import FeatureExtractionPipeline

In [13]:
from transformers import DistilBertModel, DistilBertConfig, DistilBertTokenizer

In [8]:
# Initializing a DistilBERT configuration
configuration = DistilBertConfig()

# Initializing a model from the configuration
model = DistilBertModel(`configuration)

# Accessing the model configuration
configuration = model.config

In [110]:
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertModel.from_pretrained('distilbert-base-uncased', return_dict=True)
fep = FeatureExtractionPipeline(model, tokenizer, framework='pt')

In [118]:
res = fep(text[512:1024])

In [119]:
len(res)

1

In [120]:
len(res[0])

122

In [121]:
len(res[0][0])

768

In [14]:
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertModel.from_pretrained('distilbert-base-uncased', return_dict=True)

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state

In [18]:
last_hidden_states.shape

torch.Size([1, 8, 768])

In [29]:
last_hidden_states.mean(axis=1)

tensor([[-1.0054e-01,  1.5748e-01,  1.7083e-01, -1.8576e-01,  1.7439e-01,
         -1.4498e-01,  1.6639e-01,  5.7514e-01, -2.2247e-01, -6.5292e-02,
         -3.7159e-02, -4.3940e-01, -2.3237e-01,  2.0634e-01, -4.1484e-01,
          2.2525e-01,  6.6294e-02,  1.5739e-01, -6.7144e-03,  4.6207e-01,
         -3.3887e-02, -4.5765e-01, -1.0550e-01,  2.6666e-02,  2.3136e-01,
          1.8010e-03,  1.4070e-01,  2.9723e-01,  4.4649e-02, -3.7194e-01,
          3.8288e-01, -1.7556e-01, -6.8761e-02,  1.9092e-01, -1.1435e-01,
          3.2770e-02, -1.3181e-01, -4.2276e-02, -4.9715e-01,  2.4427e-01,
         -2.0258e-01, -3.6683e-01,  2.2469e-01,  9.9785e-02, -2.2608e-01,
         -6.2989e-01, -1.2931e-01, -9.5305e-02,  4.8629e-01, -3.3055e-01,
          2.0269e-01,  1.5501e-01, -3.7417e-01, -2.3776e-02,  1.0042e-01,
          3.2745e-01, -1.1665e-01, -3.8806e-01, -7.1975e-02,  1.4425e-01,
         -1.2578e-01,  2.7368e-02,  2.8910e-01, -3.1163e-01, -2.3590e-01,
          5.1001e-01, -6.8705e-02,  1.

In [30]:
text = data.text.iloc[0]

In [32]:
inputs = tokenizer(text, return_tensors="pt")

Token indices sequence length is longer than the specified maximum sequence length for this model (12869 > 512). Running this sequence through the model will result in indexing errors


In [33]:
inputs

{'input_ids': tensor([[ 101, 4955, 3155,  ..., 1033, 1012,  102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1]])}

In [36]:
inputs['input_ids'].shape

torch.Size([1, 12869])

In [81]:
inputs = tokenizer(data.text.iloc[:2].tolist(), return_tensors="pt", padding=True)

In [82]:
inputs['input_ids'].shape

torch.Size([2, 12869])

In [85]:
get_tokens(data.text.iloc[:2].tolist())

{'input_ids': tensor([[  101,  4955,  3155,  ...,  1033,  1012,   102],
        [  101,  4955, 22935,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [88]:
split_tokens(get_tokens(data.text.iloc[:2].tolist()))[0]['input_ids'].shape

torch.Size([2, 512])

In [95]:
get_emb(data.text.iloc[1])

array([[-3.65491539e-01,  2.68735856e-01,  2.81266958e-01,
        -4.36679199e-02,  2.48239622e-01,  5.51003329e-02,
         2.06220388e-01,  6.03218563e-02, -8.39516986e-03,
         3.30531015e-03, -1.07072279e-01, -8.39443356e-02,
        -1.62238166e-01,  2.20025733e-01,  2.29168385e-01,
         4.59649086e-01,  4.03089285e-01,  1.26033768e-01,
        -1.95978526e-02,  2.34778047e-01,  4.55874950e-01,
         2.35314411e-03,  1.74211770e-01,  4.70979899e-01,
         3.32118005e-01, -2.10533768e-01,  7.00107822e-03,
        -1.15879223e-01,  3.69000435e-02,  6.28628880e-02,
         1.59018233e-01,  1.06984526e-01, -2.26293415e-01,
        -1.09240867e-01, -9.46860537e-02,  1.45582497e-01,
         8.84514675e-02, -2.76475430e-01,  8.12252238e-02,
         1.87979177e-01, -6.47739053e-01, -1.43296465e-01,
        -2.68980682e-01,  2.11763158e-01, -8.05090442e-02,
        -4.45513837e-02,  3.32733363e-01, -4.01404221e-03,
         1.24501467e-01, -8.22341740e-02, -4.40479726e-0

In [94]:
def get_tokens(text):
    return tokenizer(text, return_tensors='pt')


def split_tokens(inputs):
    new_inputs = []
    for i in range(0, inputs['input_ids'].shape[1], 512):
        input_ids = inputs['input_ids'][:, i:i+512]
        attention_mask = inputs['attention_mask'][:, i:i+512]
        new_inputs.append({'input_ids': input_ids, 'attention_mask': attention_mask})
    return new_inputs


def get_emb(text):
    emb = torch.zeros(1, 768)
#     emb = torch.zeros(len(text), 768)
    inputs = get_tokens(text)
    new_inputs = split_tokens(inputs)
    for inp in new_inputs:
        outputs = model(**inp)
        last_hidden_states = outputs.last_hidden_state
        emb += last_hidden_states.mean(axis=1)
    emb /= len(new_inputs)
    return emb.data.numpy()

In [47]:
new_inputs = []
for i in range(0, inputs['input_ids'].shape[1], 512):
    input_ids = inputs['input_ids'][:, i:i+512]
    attention_mask = inputs['attention_mask'][:, i:i+512]
    new_inputs.append({'input_ids': input_ids, 'attention_mask': attention_mask})

In [49]:
check = 0
for inp in new_inputs:
    check += inp['input_ids'].shape[1]

In [77]:
inputs['input_ids'].shape

torch.Size([1, 12869])

In [61]:
emb = torch.zeros(1, 768)
for inp in new_inputs:
    outputs = model(**inp)
    last_hidden_states = outputs.last_hidden_state
    emb += last_hidden_states.mean(axis=1)
emb

tensor([[-8.7796e+00,  3.9975e+00,  5.2408e+00,  1.4720e+00,  3.7497e+00,
          3.6517e+00,  5.6874e+00, -6.4418e-01, -6.8508e-01,  1.0185e+00,
          1.6157e+00, -5.8436e+00, -8.1801e+00,  5.8365e+00, -4.3690e-01,
          1.2110e+01,  8.8047e+00,  4.9305e-01, -1.2687e+00,  5.5927e+00,
          1.2775e+01, -1.2908e+00,  1.3705e+00,  1.3356e+01,  5.9281e+00,
         -4.1365e+00,  3.9571e+00, -1.7874e+00, -5.5498e-01,  1.9831e+00,
          6.5446e+00, -2.1814e-01, -4.0232e+00, -4.5829e+00,  4.7118e-03,
          4.4475e+00,  3.8051e+00, -3.7360e+00, -2.1668e-01,  5.4760e+00,
         -1.6906e+01, -5.5565e+00, -6.2093e+00,  3.2338e+00, -1.2379e+00,
         -3.1291e+00,  1.1838e+01,  1.1656e+00,  1.5878e+00, -2.4583e+00,
         -1.2132e+01,  8.3161e+00,  3.0254e+00,  2.1665e+00,  4.4214e+00,
          9.9880e+00, -6.0608e+00, -8.5030e+00, -9.8097e+00, -1.1179e+01,
         -2.6321e+00, -3.0147e+00,  1.2790e+00, -7.4835e+00,  2.3285e+00,
          2.3925e+00, -1.9196e+00,  1.

In [62]:
emb /= len(new_inputs)

In [69]:
pd.DataFrame(emb.data.numpy())

0         1         2         3        4        5         6    \
0 -0.337677  0.153751  0.201571  0.056614  0.14422  0.14045  0.218748   

        7         8         9    ...       758       759       760       761  \
0 -0.024776 -0.026349  0.039172  ... -0.253621 -0.054461  0.043656 -0.100731   

        762       763       764       765      766       767  
0 -0.181603 -0.575831 -0.070994  0.013752 -0.07093  0.068375  

[1 rows x 768 columns]

In [72]:
%%time
get_emb(data.text.iloc[0])

CPU times: user 17.4 s, sys: 5.08 s, total: 22.4 s
Wall time: 20.2 s


array([[-3.37676883e-01,  1.53750524e-01,  2.01570958e-01,
         5.66141419e-02,  1.44220442e-01,  1.40449733e-01,
         2.18747512e-01, -2.47760527e-02, -2.63493992e-02,
         3.91723290e-02,  6.21437170e-02, -2.24752679e-01,
        -3.14618886e-01,  2.24482596e-01, -1.68038160e-02,
         4.65776503e-01,  3.38642478e-01,  1.89633965e-02,
        -4.87960912e-02,  2.15103611e-01,  4.91347194e-01,
        -4.96479422e-02,  5.27107380e-02,  5.13691127e-01,
         2.28004515e-01, -1.59097642e-01,  1.52194411e-01,
        -6.87452257e-02, -2.13451944e-02,  7.62742832e-02,
         2.51713842e-01, -8.38991441e-03, -1.54737070e-01,
        -1.76266849e-01,  1.81223339e-04,  1.71057776e-01,
         1.46350488e-01, -1.43693775e-01, -8.33366998e-03,
         2.10615963e-01, -6.50244653e-01, -2.13712782e-01,
        -2.38819510e-01,  1.24378003e-01, -4.76108715e-02,
        -1.20350786e-01,  4.55290854e-01,  4.48289104e-02,
         6.10709563e-02, -9.45498571e-02, -4.66621250e-0

In [9]:
pd.read_csv('data_embs.csv')

0         1         2         3         4         5         6  \
0    -0.162581 -0.085848  0.090509 -0.033752  0.205265 -0.092159  0.196569   
1    -0.265050  0.095692  0.135171 -0.086902  0.249834 -0.162833  0.207181   
2    -0.166210  0.062096  0.107915 -0.107182  0.246159 -0.354403  0.203445   
3    -0.080290 -0.089464  0.147005 -0.102658  0.062539 -0.139725  0.139354   
4    -0.129327 -0.073031  0.098141 -0.090344  0.093056 -0.121724  0.147562   
...        ...       ...       ...       ...       ...       ...       ...   
2997 -0.139089  0.053157  0.050308 -0.051250  0.168996 -0.141922  0.067989   
2998 -0.249892  0.013647  0.019110 -0.042661  0.135654 -0.072846  0.202105   
2999 -0.184074 -0.093682  0.027090 -0.083272  0.284870  0.029592  0.185686   
3000 -0.063675  0.029488  0.035511 -0.063895  0.450002 -0.122640  0.158073   
3001 -0.177170 -0.029327  0.119568 -0.039308  0.158167  0.008605  0.206632   

             7         8         9  ...       758       759       760  \
0     0.056438 -0.022002  0.002166  ...  0.110439  0.091388 -0.033890   
1     0.063791 -0.035453  0.042912  ...  0.004523 -0.086509 -0.077419   
2     0.108149 -0.060827  0.160299  ...  0.100083 -0.054048 -0.067550   
3     0.091616  0.164334 -0.152841  ...  0.244334  0.109327 -0.017169   
4     0.054889  0.116375 -0.114047  ...  0.185564  0.062140 -0.037500   
...        ...       ...       ...  ...       ...       ...       ...   
2997  0.083257  0.025823  0.002579  ...  0.057098  0.044541 -0.226393   
2998  0.088568  0.003533  0.085708  ... -0.107333 -0.032451 -0.174745   
2999  0.190774  0.024570 -0.015983  ...  0.036028  0.085632 -0.068538   
3000  0.174713  0.009652 -0.030548  ... -0.017369  0.037358 -0.029856   
3001  0.099556  0.087689 -0.074154  ...  0.063741 -0.062041 -0.051877   

           761       762       763       764       765       766       767  
0    -0.060766 -0.038924 -0.231480 -0.066054 -0.134102  0.009384  0.162927  
1     0.047831 -0.000789 -0.161356 -0.080066 -0.219771 -0.158743  0.156257  
2     0.100403 -0.060425 -0.228944  0.074979 -0.221526 -0.134613  0.175024  
3    -0.176257  0.157510 -0.316807 -0.154248 -0.075818  0.154728  0.151226  
4    -0.160846  0.057113 -0.277370 -0.115096 -0.105955  0.096991  0.130266  
...        ...       ...       ...       ...       ...       ...       ...  
2997 -0.337473 -0.125724 -0.265817 -0.054392 -0.181950  0.046370  0.086473  
2998 -0.074873 -0.033087 -0.225026 -0.204773 -0.278338 -0.034773  0.020825  
2999 -0.255393 -0.059604 -0.255831 -0.174241 -0.175819  0.098475  0.064971  
3000 -0.017334 -0.168212 -0.231745 -0.052308 -0.154873 -0.091601  0.136982  
3001 -0.265463 -0.079427 -0.251122 -0.175231 -0.123115  0.048007  0.135635  

[3002 rows x 768 columns]

In [15]:
from sklearn.cluster import DBSCAN

In [16]:
dbscan = DBSCAN()

In [15]:
%%time
preds = dbscan.fit_predict(pd.read_csv('data_embs.csv').values)

CPU times: user 9.97 s, sys: 86.5 ms, total: 10.1 s
Wall time: 10.1 s


In [17]:
from sklearn.cluster import KMeans

In [27]:
kmeans = KMeans(2)

In [4]:
X = pd.read_csv('data_embs.csv').values

In [28]:
preds = kmeans.fit_predict(pd.read_csv('data_embs.csv').values)

In [29]:
for i in range(2):
    print((preds==i).sum())
print(len(preds))

1472
1530
3002


In [30]:
data.discipline.value_counts()

Biomedicine                 1857
Medicine & Public Health    1145
Name: discipline, dtype: int64

In [31]:
from sklearn.cluster import spectral_clustering

In [35]:
from sklearn import metrics

In [5]:
y = data.discipline.astype('category').cat.codes

In [42]:
metrics.adjusted_rand_score(y, preds)

-0.00015787016253032387

In [6]:
from sklearn.cluster import AgglomerativeClustering

In [9]:
model = AgglomerativeClustering(affinity='cosine', linkage='complete')

In [10]:
model.fit(X)

AgglomerativeClustering(affinity='cosine', linkage='complete')

In [12]:
preds = model.fit_predict(X)

In [14]:
for i in range(2):
    print((preds==i).sum())
print(len(preds))

2619
383
3002


In [17]:
preds = DBSCAN(metric='cosine').fit_predict(X)

In [4]:
texts = data.text.tolist()

In [8]:
len(texts[0].replace('\n', ' ').split())

7192

In [9]:
lenghts = [len(text.replace('\n', ' ').split()) for text in texts]
sum(lenghts) / len(lenghts)

4629.128914057295

In [10]:
min(lenghts), max(lenghts)

(1549, 26309)

In [12]:
texts[0]

'Introduction\nApproximately 7% of the world’s population suffers from neuropathic pain in their lifetime [ ]. Although there are multiple drugs for the treatment of this disorder, opioids remain the last option of prescribed management for moderate to severe neuropathic pain. However, most of neuropathic pain patients require high doses of opioids as well as repeated and prolonged administration of opioids to alleviate pain. The side effects of opioids significantly limit their use in neuropathic pain patients. Increasing evidence demonstrated that unsatisfactory pain relief under neuropathic pain conditions may result, at least in part, from nerve injury–induced changes in gene transcription and translation of receptors (e.g., opioid receptor downregulation), voltage-dependent channels (e.g., voltage-gated potassium channel subunit Kv1.2 downregulation), and enzymes in the first-order sensory neurons of the ipsilateral dorsal root ganglion (DRG) [ , ]. Therefore, targeting the molecu